default:
  image: hectorlachambre/oc-expert-devops-angular-python
  retry: 2
  before_script:
    - python3 -m pip install typer
    - npm ci --cache .npm --prefer-offline
    - ./node_modules/.bin/ng serve

stages:
  - build
  - test
  - package
  - publish

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

build_application:
  stage: build
  script:
    - ./java-ci.py build
  artifacts:
    paths:
      - build/*

test_application:
  stage: test
  script:
    - ./java-ci.py test
  artifacts:
    reports:
      junit: build/reports/tests/test/index.html

package_application:
  stage: package
  script:
    - python3 ./java-ci.py pack
  artifacts:
    name: ci-package-result
    paths:
      - build/libs/*.war
    expire_in: 1 week

publish_application:
  stage: publish
  when: manual
  script:
    - python3 ./java-ci.py publish
