default:
  image: hectorlachambre/oc-expert-devops-java-python
  retry: 2
  before_script:
    - python3 -m pip install typer

stages:
  - build
  - test
  - package
  - publish

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

